In [ ]:
# Importing libraries
import numpy as np
import pandas as pd
from scipy.stats import mode
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
%matplotlib inline

In [ ]:
data=pd.read_csv('/Users/Albert3/Downloads/alldata.csv')
df=data[['Drug Name','Cell Line Name','Tissue','Tissue Sub-type','IC50']]
df

Drug Name Cell Line Name                Tissue Tissue Sub-type  \
0           Camptothecin           TE-5  aero_digestive_tract      oesophagus   
1           Camptothecin       EC-GI-10  aero_digestive_tract      oesophagus   
2           Camptothecin          HCE-4  aero_digestive_tract      oesophagus   
3           Camptothecin       KYSE-140  aero_digestive_tract      oesophagus   
4           Camptothecin       KYSE-410  aero_digestive_tract      oesophagus   
...                  ...            ...                   ...             ...   
90996  N-acetyl cysteine           FU97      digestive_system         stomach   
90997  N-acetyl cysteine         NUGC-4      digestive_system         stomach   
90998  N-acetyl cysteine         OCUM-1      digestive_system         stomach   
90999  N-acetyl cysteine         HSC-39      digestive_system         stomach   
91000  N-acetyl cysteine        SK-GT-2      digestive_system         stomach   

            IC50  
0      -2.555311  
1      -3.125664  
2      -3.536140  
3      -0.402974  
4       0.605862  
...          ...  
90996  10.541691  
90997   9.745149  
90998  10.959875  
90999   8.342217  
91000  10.192296  

[91001 rows x 5 columns]

In [ ]:
encoder = LabelEncoder()
dframe=pd.DataFrame()
dframe["Drug Name"] = encoder.fit_transform(df["Drug Name"])
dframe["Cell Line Name"] = encoder.fit_transform(df["Cell Line Name"])
dframe["Tissue"] = encoder.fit_transform(df["Tissue"])
dframe["Tissue Sub-type"] = encoder.fit_transform(df["Tissue Sub-type"])
dframe['IC50']=df['IC50']
dframe

In [ ]:
#X and Y
X=dframe[['Cell Line Name','Tissue','Tissue Sub-type','IC50']]
Y=dframe[['Drug Name']]

In [ ]:
#scaling
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
X=scaler.fit_transform(X)
X

array([[ 1.69345217, -2.30592897,  1.16613602, -2.07469148],
       [-1.32157697, -2.30592897,  1.16613602, -2.28448591],
       [-0.93211747, -2.30592897,  1.16613602, -2.4354723 ],
       ...,
       [ 0.77887875, -0.25873143,  1.92319793,  2.89663228],
       [-0.84459848, -0.25873143,  1.92319793,  1.93377265],
       [ 1.27336103, -0.25873143,  1.92319793,  2.61429184]])

In [ ]:
#Split the dataset
X_train, X_test, y_train, y_test =train_test_split(X, Y, test_size = 0.1, random_state = 24)
print(f"Train: {X_train.shape}, {y_train.shape}")
print(f"Test: {X_test.shape}, {y_test.shape}")

Train: (81900, 4), (81900, 1)
Test: (9101, 4), (9101, 1)


In [ ]:
# Training and testing Random Forest Classifier
rf_model = RandomForestClassifier(random_state=18)
rf_model.fit(X, Y)

/var/folders/d9/f8xx3ggn7y5f7tr2jyd4nkk80000gp/T/ipykernel_4887/638098497.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf_model.fit(X, Y)


RandomForestClassifier(random_state=18)

In [ ]:
preds = rf_model.predict(X_test)
preds

array([233, 244, 166, ..., 172, 268, 270])

In [ ]:
#predict a specific value
scaled_x=scaler.transform([[203,4,50,10.541691]])
scaled_x

/Users/Albert3/miniconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.15091494, -0.25873143,  1.92319793,  2.74281057]])

In [ ]:
predicted=rf_model.predict([scaled_x[0]])

In [ ]:
predicted

array([174])

In [ ]:
print(f"Accuracy on train data by Random Forest Classifier\
: {accuracy_score(y_train, rf_model.predict(X_train))*100}")

Accuracy on train data by Random Forest Classifier: 99.52014652014653


In [ ]:
print(f"Accuracy on test data by Random Forest Classifier\
: {accuracy_score(y_test, preds)*100}")

Accuracy on test data by Random Forest Classifier: 99.5934512690913


In [ ]:
#join the encoded file and the original dataframe
tframe=df.join(dframe,rsuffix='enc')
tframe

Drug Name Cell Line Name                Tissue Tissue Sub-type  \
0           Camptothecin           TE-5  aero_digestive_tract      oesophagus   
1           Camptothecin       EC-GI-10  aero_digestive_tract      oesophagus   
2           Camptothecin          HCE-4  aero_digestive_tract      oesophagus   
3           Camptothecin       KYSE-140  aero_digestive_tract      oesophagus   
4           Camptothecin       KYSE-410  aero_digestive_tract      oesophagus   
...                  ...            ...                   ...             ...   
90996  N-acetyl cysteine           FU97      digestive_system         stomach   
90997  N-acetyl cysteine         NUGC-4      digestive_system         stomach   
90998  N-acetyl cysteine         OCUM-1      digestive_system         stomach   
90999  N-acetyl cysteine         HSC-39      digestive_system         stomach   
91000  N-acetyl cysteine        SK-GT-2      digestive_system         stomach   

            IC50  Drug Nameenc  Cell Line Nameenc  Tissueenc  \
0      -2.555311            73                853          0   
1      -3.125664            73                164          0   
2      -3.536140            73                253          0   
3      -0.402974            73                379          0   
4       0.605862            73                384          0   
...          ...           ...                ...        ...   
90996  10.541691           174                203          4   
90997   9.745149           174                631          4   
90998  10.959875           174                644          4   
90999   8.342217           174                273          4   
91000  10.192296           174                757          4   

       Tissue Sub-typeenc    IC50enc  
0                      42  -2.555311  
1                      42  -3.125664  
2                      42  -3.536140  
3                      42  -0.402974  
4                      42   0.605862  
...                   ...        ...  
90996                  50  10.541691  
90997                  50   9.745149  
90998                  50  10.959875  
90999                  50   8.342217  
91000                  50  10.192296  

[91001 rows x 10 columns]

In [ ]:
#predict actual values
cln='EC-GI-10'
tis='aero_digestive_tract'
subt='oesophagus'
i50=-3.125664
test=pd.DataFrame()
test['clnenc']=tframe['Cell Line Nameenc'].where((tframe['Cell Line Name']==cln))
test['tis']=tframe['Tissueenc'].where((tframe['Tissue']==tis))
test['subt']=tframe['Tissue Sub-typeenc'].where((tframe['Tissue Sub-type']==subt))
test['ic50']=-3.125664
test.dropna(inplace=True)
x=np.array(test.iloc[0,0:])
x

array([164.      ,   0.      ,  42.      ,  -3.125664])

In [ ]:
#scale the input values
scaled_x=scaler.transform([x])
scaled_x

/Users/Albert3/miniconda3/lib/python3.9/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-1.32157697, -2.30592897,  1.16613602, -2.28448589]])

In [ ]:
#predict drug encode
drugenc=rf_model.predict([scaled_x[0]])
drugenc[0]

73

In [ ]:
#return the drugname
drugname=tframe['Drug Name'].where(tframe['Drug Nameenc']==drugenc[0])
drugname.dropna(inplace=True)
drugname.iloc[0]

'Camptothecin'

In [ ]:
#Save the classifier
import joblib
joblib.dump(rf_model,'rfclassifier.joblib',compress=5)

['rfclassifier.joblib']